# RuntipiOS Build Configuration
# Modify this file to customize the build

# Base system configuration
base:
  distribution: debian
  release: bookworm
  architecture: amd64
  
# ISO configuration
iso:
  name: RuntipiOS
  version: 1.0.0
  label: RUNTIPIOS
  
# Packages to include
packages:
  # Base system
  - linux-image-amd64
  - live-boot
  - systemd-sysv
  
  # Network tools
  - network-manager
  - wireless-tools
  - wpasupplicant
  - iw
  - rfkill
  
  # SSH
  - openssh-server
  
  # System utilities
  - sudo
  - curl
  - wget
  - git
  - vim
  - nano
  
  # Docker for Runtipi
  - docker.io
  - docker-compose
  
  # GUI for installer
  - python3
  - python3-tk
  - python3-pip
  - dialog
  - whiptail
  
  # WiFi Connect dependencies
  - dnsmasq
  - hostapd
  - python3-flask
  - python3-requests
  - python3-netifaces

# Runtipi configuration
runtipi:
  repository: https://github.com/runtipi/runtipi
  install_path: /opt/runtipi
  auto_start: true
  
# First boot configuration
firstboot:
  enable_ssh: true
  create_user: true
  configure_network: true
  install_runtipi: true
  
# WiFi Connect configuration
wifi_connect:
  enabled: true
  portal_ssid: "RuntipiOS-Setup"
  portal_password: ""
  portal_interface: wlan0
  portal_address: 192.168.42.1
  portal_dhcp_range: "192.168.42.10,192.168.42.100"
